# Generated by Django 2.1.4 on 2019-04-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('continent', models.CharField(choices=[('Westeros', 'Westeros'), ('Essos', 'Essos'), ('Unknown', 'Unknown')], max_length=20)),
            ],
            options={
                'ordering': ['name', 'continent'],
            },
        ),
    ]
